/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_657f9657 (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/tcmmddpcihkohnytxmeh/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
// Modified to support Row Level Security (RLS) by accepting user access tokens.
import { createClient } from "jsr:@supabase/supabase-js@2.49.8";

// Create a Supabase client using service role key (bypasses RLS)
const serviceRoleClient = () => createClient(
  Deno.env.get("SUPABASE_URL"),
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),
);

// Create a Supabase client using user's access token (respects RLS)
const userClient = (accessToken: string) => createClient(
  Deno.env.get("SUPABASE_URL"),
  Deno.env.get("SUPABASE_ANON_KEY"),
  {
    global: {
      headers: {
        Authorization: `Bearer ${accessToken}`,
      },
    },
  }
);

// Get the appropriate client based on whether an access token is provided
const client = (accessToken?: string) => {
  return accessToken ? userClient(accessToken) : serviceRoleClient();
};

// Set stores a key-value pair in the database.
// Pass accessToken to respect RLS, or omit for service role access.
export const set = async (key: string, value: any, accessToken?: string): Promise<void> => {
  const supabase = client(accessToken)
  const { error } = await supabase.from("kv_store_657f9657").upsert({
    key,
    value
  });
  if (error) {
    throw new Error(error.message);
  }
};

// Get retrieves a key-value pair from the database.
// Pass accessToken to respect RLS, or omit for service role access.
export const get = async (key: string, accessToken?: string): Promise<any> => {
  const supabase = client(accessToken)
  const { data, error } = await supabase.from("kv_store_657f9657").select("value").eq("key", key).maybeSingle();
  if (error) {
    throw new Error(error.message);
  }
  return data?.value;
};

// Delete deletes a key-value pair from the database.
// Pass accessToken to respect RLS, or omit for service role access.
export const del = async (key: string, accessToken?: string): Promise<void> => {
  const supabase = client(accessToken)
  const { error } = await supabase.from("kv_store_657f9657").delete().eq("key", key);
  if (error) {
    throw new Error(error.message);
  }
};

// Sets multiple key-value pairs in the database.
// Pass accessToken to respect RLS, or omit for service role access.
export const mset = async (keys: string[], values: any[], accessToken?: string): Promise<void> => {
  const supabase = client(accessToken)
  const { error } = await supabase.from("kv_store_657f9657").upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
  if (error) {
    throw new Error(error.message);
  }
};

// Gets multiple key-value pairs from the database.
// Pass accessToken to respect RLS, or omit for service role access.
export const mget = async (keys: string[], accessToken?: string): Promise<any[]> => {
  const supabase = client(accessToken)
  const { data, error } = await supabase.from("kv_store_657f9657").select("value").in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};

// Deletes multiple key-value pairs from the database.
// Pass accessToken to respect RLS, or omit for service role access.
export const mdel = async (keys: string[], accessToken?: string): Promise<void> => {
  const supabase = client(accessToken)
  const { error } = await supabase.from("kv_store_657f9657").delete().in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
};

// Search for key-value pairs by prefix.
// Pass accessToken to respect RLS, or omit for service role access.
export const getByPrefix = async (prefix: string, accessToken?: string): Promise<any[]> => {
  const supabase = client(accessToken)
  const { data, error } = await supabase.from("kv_store_657f9657").select("key, value").like("key", prefix + "%");
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};